"""empty message

Revision ID: daaee90cc855
Revises: 
Create Date: 2026-03-16 05:09:06.721544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaee90cc855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_persons', schema=None) as batch_op:
        batch_op.drop_column('enrolled_profile')
        batch_op.drop_column('enrolled_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled_class', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('enrolled_profile', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
