"""empty message

Revision ID: fd41150079a5
Revises: daaee90cc855
Create Date: 2026-03-16 05:13:01.899024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd41150079a5'
down_revision = 'daaee90cc855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('enrolled_profile', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('com_persons', schema=None) as batch_op:
        batch_op.drop_column('enrolled_profile')
        batch_op.drop_column('enrolled_class')

    # ### end Alembic commands ###
